### ISSUE TITLE
[requirer] A custom event for relation broken is missing

### ISSUE THREAD

**Issue by sed-i** [canonical/certificate-transfer-interface#5]
Currently we use `certificate_available` for adding a cert, but there is no parallel for removing a cert.

**Comment by lucabello** [comment]
@ghislainbourgeois @gruyaume gentle ping on this as this is a blocker for our TLS implementation :)

**Comment by gruyaume** [comment]
Ack, added to our backlog

**Comment by gatici** [comment]
@lucabello @sed-i  PR: https://github.com/canonical/certificate-transfer-interface/pull/18 is merged which solves this issue. Please confirm if we could close this bug ?

**Comment by lucabello** [comment]
We're almost there; even though that PR adds a `certificate_removed` event, it doesn't carry the **`relation_id`** information that would be necessary to figure out which certificate to delete on the requirer side (in case of multiple relations).
